### ISSUE TITLE
Make sure selected shapes have an equal chance of being chosen for the next scramble

### ISSUE THREAD

**Issue by sp3ctum** [sp3ctum/squanmate#21]
See https://www.speedsolving.com/forum/threads/scrambler-algorithm-discussion.66097/#post-1252127 and the thread for discussion.

**Comment by sp3ctum** [comment]
The link above is concerned more about whether WCA scrambling has an equal chance for cubeshape cases to occur. Squanmate has an equal chance for all selected cases.

For example, if you have selected 5 star cases and square square, each of these cases has a 1/6 chance of being selected for the next scramble.

**Comment by bugybunny** [comment]
So you didn’t change anything for this issue, right in the last month, did you? I saw this open issue sometimes when I created a new one but just read the title, not your comment. And I always thought I should comment sometimes because I like the actual “mode”. I often have all Square cases selected to repeat and not forget them and then I get Left Pawn/Square like 3 times in a row , then another x/Square and then again Left Pawn/Square. And I thought this is intentional and you wanted to change that. I really like it and it helps me train the cases when they occur more frequently in a short time and then switch to a different shape.

But as it seems now it was just luck and Squanmate does not have like an “intelligent” trainer to select shapes for the best learning experience. Just something I wanted to add as information.

**Comment by sp3ctum** [comment]
Yeah it's completely random. I thought about this kind of suggestive
randomness but I thought it would be tricky and confusing to users as well.

The way I use it is whenever I feel like I have had an easy time with a
case, I deselect that case. That way I feel like I can spend my time on the
difficult cases only.

**Comment by bugybunny** [comment]
Ok, so it’s really good luck :D It definitely does not feel random, I’m getting so many Scallop/Square, around 3 times of the other cases I get. [But you can never be sure with randomness ](http://assets.amuniversal.com/321a39e06d6401301d80001dd8b71c47)  ¯\_(ツ)_/¯
