### ISSUE TITLE
Extra commas in algorithms should throw an error

### ISSUE THREAD

**Issue by bugybunny** [sp3ctum/squanmate#44]
For example in the algorithm shape visualizer https://rawgit.com/sp3ctum/squanmate/master/resources/public/#/shape-visualizer/square/left-pawn/(-5%2C-4)/(-1%2C0)%2F1%2C0%2F0%2C-2%2C%2F-1%2C-2%2F

Screenshot for later when this is fixed
![image](https://user-images.githubusercontent.com/5311105/35016345-6d77aea6-fb18-11e7-8615-3a9bb466b9cd.png)

Notice the extra comma in `0,-2,/`. I accidentally wrote that and could not figure out for a long time why the images were not generated for a part of the algorithm :D I would suggest, that Squanmate should check for multiple commas between two slashes and if it’s illegal, just throw an error as an unsliceable position does. I guess Squanmate does already do something like this because the visualization just stops because of an error I guess.

This is not only in the alg shape visualizer but also the scramble inspector. If I enter ` 1,0/-1,0,/-3,0/` I get just 
![image](https://user-images.githubusercontent.com/5311105/35016515-2eb5ef06-fb19-11e7-9776-39fd69253937.png)

Not only commas are a problem, but every other illegal character. If you already check if something in the algorithm is legal and get no as an answer, just pass the error to the user.

**Comment by sp3ctum** [comment]
Oops, this is definitely a bug. Good find.

**Comment by sp3ctum** [comment]
Okay, I managed to fix this (https://github.com/sp3ctum/squanmate/commit/319ee7c). Here's what your case looks now:

![image](https://user-images.githubusercontent.com/300791/35149283-2ca5bc12-fd1e-11e7-884c-ee9ce4c1edca.png)

The error message may be a bit confusing. Basically the algorithm parser looks for a slice, rotations, or a `*` character, or the end of the algorithm. It hasn't found the previous ones at that position, so it's only expecting the algorithm to end.

But at least it shows the position where the error is now, instead of hiding it.
