### ISSUE TITLE
Squanmate should not put a space after a / when showing algorithms

### ISSUE THREAD

**Issue by bugybunny** [sp3ctum/squanmate#45]
Squanmate always puts a space after a `/` in Sq1 notation. This has been bugging me a lot since I started using Squanmate but I was always too lazy to open an issue.

E.g. when importing a scramble I enter `1,0/-1,0/` and after the import Squanmate displays
![image](https://user-images.githubusercontent.com/5311105/35016659-e9e1e078-fb19-11e7-808e-6da685d41add.png)

So it is transformed to `(1,0)/ (-1,0)/`. Happens also in the algorithm shape visualizer and everywhere else where algs are shown. Either also make a space before the `/` or neither before or after (I think I prefer the one without spaces. I tested both versions by changing the HTML with the DevTools and it is still readable without the spaces and more compact=better).

Btw: I like the new asterisk that shows when we leave the cubeshape :) My hand/brain coordination already tells me this when reading the last numbers before we leave cubeshape because I’ve done thousands of scrambles but I still like it :)
Edit: ok just saw the highlighting. I don’t like that at all <.< Just because text selection can be done by the user and is used for something else already (a user action, not normally something an application does).

**Comment by sp3ctum** [comment]
Good suggestion. Originally putting a space like that was a hack to get the algorithm to wrap nicely. Now I have a more advanced solution to wrapping in mind so the space can be removed though.

**Comment by sp3ctum** [comment]
The idea with the asterisks and highlighting is to
- allow shape shifted scrambles to be executed without the initial 10 or so cubeshape preserving moves. Sometimes I wanted to quickly get the puzzle to a specific shape cases so I can drill my algs in that state, and this makes it faster
- easier to follow along. Sometimes I left cubeshape early and wasted time because I misscrambled
- now it's an additional check to see if I'm leaving cubeshape with the puzzle aligned or misaligned. So even if I mess up the first part of the scramble, I can still get to the shape case I originally wanted

**Comment by sp3ctum** [comment]
I can make the highlighting a bit more subtle. I'll open another issue for that.

**Comment by sp3ctum** [comment]
I implemented this today too, but it isn't released yet. I made it so that each (1,2)/ (rotations and slice instructions) always sticks together when the algorithm doesn't fit on one line (is wrapped).

With this I tried to make the algorithm displayed consistently, so the slice should never wrap to the start of the next line.

**Comment by sp3ctum** [comment]
Fixed by https://github.com/sp3ctum/squanmate/commit/1662529 and released in version 6.6
