### ISSUE TITLE
Add keyboard shortcuts for trainers

### ISSUE THREAD

**Issue by sp3ctum** [sp3ctum/squanmate#49]
There is a great framework for using page-wide keyboard shortcuts in place, but only one page uses it so far (the parity game).

Currently the UI is slightly geared towards a mobile device. Laptop / desktop users might benefit a lot from easy to use keyboard bindings.

**Comment by sp3ctum** [comment]
@bugybunny if you have the time, I would like to hear your thoughts on this.

I have one idea so far:
- have a button with a keyboard icon, which displays a cheat sheet of all the key bindings for the current page
- for the cubeshape trainer, the bindings could be something like this:
- `space` new scramble
- `r r` repeat the current case with random parity
- `r s` repeat with same parity, `r o` repeat with other parity
- `i` start inspection timer if it's visible

What do you think? Would that be nice to use?

**Comment by bugybunny** [comment]
Yeah, keyboard shortcuts, especially some that are good to use with my keyboard layout (NEO layout)! I rarely use it on mobile so it would benefit me—and hopefully others—a lot. I just always set the focus to the `New Scramble` button and then used space to trigger it and I rarely use the other features  but I can see myself using them more in the future when I know more cases.

I like all of your ideas, they are intuitive and will be easy to remember. I have just a few thoughts about `space`.

* As I said above, space is generally used to trigger the action of the currently focused element.
* On the other hand, all webbased timers use space to start/stop. So I don't see it as problem.
* I just discovered the inspection timer for the first time yesterday and wanted to create an issue for some enhancements (will do that later). Among other things, I would like to to have the ability to stop the timer again to see how long it took me (then you could even create statistics later for inspection time for each case etc.). So `i` for start and stop could be used. But I guess many people would intuitively use `space` because of the other timers they know.
* But I would still go with `i` for timer and `space` for new scramble because it will be the most used function.
* I'm not fully happy with `space` because it takes away the default behavior and does not follow the convention of activating the action of the focused element. However, space is a big key, hard to miss (than say e.g. `n` for new scramble) and you don't really have to think about where to press with one hand (also useful for people like me that have a blank keyboard :D I often have to place both hands on the keyboard because I'm not entirely sure where to press). So in the end I'm for `space` for the new scramble feature.
* Just keep in mind thet you may add new features that need a shortcut in the future and already think about possible shortcuts there. I would be bad to later change the shortcuts again.

**Comment by sp3ctum** [comment]
Okay, great to hear. I think this definitely calls for some thinking about whether Squanmate should be a trainer, a trainer with a basic timer, or "everything related to Squan" with a full featured timer with display of running averages and other features.

There already is cstimer, and twisty timer, which are good and popular. They have a lot of features too, but they are of course much more general, ones that benefit every timeable puzzle.

But for example related to the inspection timer, as a Squan solver, I wanted to practice inspection for a subset of all the shape cases. Because there is no other tool for this purpose, I saw it as justification for adding a timer like feature to Squanmate.

But I have to draw the line somewhere, otherwise someone will come asking for a feature to export times, then someone wants a background image, etc.

🤔

**Comment by sp3ctum** [comment]
Shortcuts are now in version 6.8. Let me know what you think!

**Comment by bugybunny** [comment]
I haven’t used them much as I mostly only use New Scramble. It’s a bit more convenient that the focus does not have to be on the button to trigger the action with space. I have used the new Repeat and flip top and bottom layers a few times.

Is there a reason `i` for starting the timer has not been implemented or did you just forget it?

**Comment by sp3ctum** [comment]
Is there a reason i for starting the timer has not been implemented or did
you just forget it?

Actually I had some hand pain and had to stop typing. The implementation
will probably come at some point. I'm not sure how my health will hold up
yet.
